version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - dashboard-network
  dashboard:
    image: mrrs878/dashboard
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - dashboard-network
networks:
  dashboard-network:
    driver: bridge