version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - monitor_backend-network
  monitor_backend:
    image: mrrs878/monitor_backend:latest
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - monitor_backend-network
networks:
  monitor_backend-network:
    driver: bridge
