version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - dashboard_backend-network
  dashboard_backend:
    image: mrrs878/dashboard_backend:latest
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - dashboard_backend-network
networks:
  dashboard_backend-network:
    driver: bridge