version: '3.7'
services:
  backend_database:
    image: mysql
    container_name: backend_database
    restart: always
    ports:
      - 8084:3306
    volumes:
      - ~/data/backend_database:/data/db
    networks:
      - backend-n-mysql
  backend_cache:
    image: redis:alpine
    container_name: backend_cache
    restart: always
    ports:
      - 8085:6379
    volumes:
      - ~/cache/backend_cache:/data
    networks:
      - backend-n-redis
    command: --appendonly yes
  backend:
    image: mrrs878/backend:latest
    container_name: backend
    volumes:
      - ~/log/backend:/app/log
    depends_on:
      - backend_database
      - backend_cache
    ports:
      - 3000:3000
    networks:
      - backend-n-mysql
      - backend-n-redis
networks:
  backend-n-mysql:
    driver: bridge
  backend-n-redis:
    driver: bridge