version: '3.7'
services:
  monitor_database:
    image: mongo
    container_name: monitor_database
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - monitor_backend-network
  monitor_backend:
    image: mrrs878/monitor_backend:latest
    container_name: monitor_backend
    depends_on:
      - monitor_database
    ports:
      - 3000:3000
    networks:
      - monitor_backend-network
networks:
  monitor_backend-network:
    driver: bridge
