version: '3.7'
services:
  blog_database:
    image: mongo
    container_name: blog_database
    restart: always
    volumes:
      - ~/data/blog_backend:/data/db
    networks:
      - blog_backend-network
  blog_backend:
    image: mrrs878/blog_backend:latest
    container_name: blog_backend
    depends_on:
      - blog_database
    ports:
      - 3000:3000
    networks:
      - blog_backend-network
networks:
  blog_backend-network:
    driver: bridge
